python main.py \
--bert_dir="../../model_hub/hfl_chinese-roberta-wwm-ext/" \
--data_dir="./data/" \
--log_dir="./logs/" \
--output_dir="./checkpoints/" \
--num_tags=218 \
--seed=123 \
--gpu_ids="0" \
--max_seq_len=320 \
--lr=2e-5 \
--other_lr=2e-4 \
--train_batch_size=32 \
--train_epochs=10 \
--eval_batch_size=32
